/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.uimanager.ViewManagerWithGeneratedInterface;

public interface StrokeTextViewManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setWidth(T view, float value);
  void setText(T view, @Nullable String value);
  void setFontSize(T view, float value);
  void setColor(T view, @Nullable String value);
  void setStrokeColor(T view, @Nullable String value);
  void setStrokeWidth(T view, float value);
  void setFontFamily(T view, @Nullable String value);
  void setAlign(T view, @Nullable String value);
  void setNumberOfLines(T view, int value);
  void setEllipsis(T view, boolean value);
}
