
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>

namespace facebook::react {

enum class StrokeTextViewAlign { Center, Left, Right };

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, StrokeTextViewAlign &result) {
  auto string = (std::string)value;
  if (string == "center") { result = StrokeTextViewAlign::Center; return; }
  if (string == "left") { result = StrokeTextViewAlign::Left; return; }
  if (string == "right") { result = StrokeTextViewAlign::Right; return; }
  abort();
}

static inline std::string toString(const StrokeTextViewAlign &value) {
  switch (value) {
    case StrokeTextViewAlign::Center: return "center";
    case StrokeTextViewAlign::Left: return "left";
    case StrokeTextViewAlign::Right: return "right";
  }
}

#ifdef RN_SERIALIZABLE_STATE
static inline folly::dynamic toDynamic(const StrokeTextViewAlign &value) {
  return toString(value);
}
#endif

class StrokeTextViewProps final : public ViewProps {
 public:
  StrokeTextViewProps() = default;
  StrokeTextViewProps(const PropsParserContext& context, const StrokeTextViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  Float width{0.0};
  std::string text{};
  Float fontSize{0.0};
  std::string color{};
  std::string strokeColor{};
  Float strokeWidth{0.0};
  std::string fontFamily{};
  StrokeTextViewAlign align{StrokeTextViewAlign::Center};
  int numberOfLines{0};
  bool ellipsis{false};

  #ifdef RN_SERIALIZABLE_STATE
  ComponentName getDiffPropsImplementationTarget() const override;

  folly::dynamic getDiffProps(const Props* prevProps) const override;
  #endif
};

} // namespace facebook::react
