
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/StrokeTextView/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook::react {

StrokeTextViewProps::StrokeTextViewProps(
    const PropsParserContext &context,
    const StrokeTextViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    width(convertRawProp(context, rawProps, "width", sourceProps.width, {0.0})),
    text(convertRawProp(context, rawProps, "text", sourceProps.text, {})),
    fontSize(convertRawProp(context, rawProps, "fontSize", sourceProps.fontSize, {0.0})),
    color(convertRawProp(context, rawProps, "color", sourceProps.color, {})),
    strokeColor(convertRawProp(context, rawProps, "strokeColor", sourceProps.strokeColor, {})),
    strokeWidth(convertRawProp(context, rawProps, "strokeWidth", sourceProps.strokeWidth, {0.0})),
    fontFamily(convertRawProp(context, rawProps, "fontFamily", sourceProps.fontFamily, {})),
    align(convertRawProp(context, rawProps, "align", sourceProps.align, {StrokeTextViewAlign::Center})),
    numberOfLines(convertRawProp(context, rawProps, "numberOfLines", sourceProps.numberOfLines, {0})),
    ellipsis(convertRawProp(context, rawProps, "ellipsis", sourceProps.ellipsis, {false})) {}
    
#ifdef RN_SERIALIZABLE_STATE
ComponentName StrokeTextViewProps::getDiffPropsImplementationTarget() const {
  return "StrokeTextView";
}

folly::dynamic StrokeTextViewProps::getDiffProps(
    const Props* prevProps) const {
  static const auto defaultProps = StrokeTextViewProps();
  const StrokeTextViewProps* oldProps = prevProps == nullptr
      ? &defaultProps
      : static_cast<const StrokeTextViewProps*>(prevProps);
  if (this == oldProps) {
    return folly::dynamic::object();
  }
  folly::dynamic result = HostPlatformViewProps::getDiffProps(prevProps);
  
  if ((width != oldProps->width) && !(std::isnan(width) && std::isnan(oldProps->width))) {
    result["width"] = width;
  }
    
  if (text != oldProps->text) {
    result["text"] = text;
  }
    
  if ((fontSize != oldProps->fontSize) && !(std::isnan(fontSize) && std::isnan(oldProps->fontSize))) {
    result["fontSize"] = fontSize;
  }
    
  if (color != oldProps->color) {
    result["color"] = color;
  }
    
  if (strokeColor != oldProps->strokeColor) {
    result["strokeColor"] = strokeColor;
  }
    
  if ((strokeWidth != oldProps->strokeWidth) && !(std::isnan(strokeWidth) && std::isnan(oldProps->strokeWidth))) {
    result["strokeWidth"] = strokeWidth;
  }
    
  if (fontFamily != oldProps->fontFamily) {
    result["fontFamily"] = fontFamily;
  }
    
  if (align != oldProps->align) {
    result["align"] = toDynamic(align);
  }
    
  if (numberOfLines != oldProps->numberOfLines) {
    result["numberOfLines"] = numberOfLines;
  }
    
  if (ellipsis != oldProps->ellipsis) {
    result["ellipsis"] = ellipsis;
  }
  return result;
}
#endif

} // namespace facebook::react
